---
## Author
author:
  name: Добрынин Никита Артёмович
  email: 1132255598@rudn.ru
  affiliation:
    - name: Российский университет дружбы народов
      country: Российская Федерация
      postal-code: 117198
      city: Москва
      address: ул. Миклухо-Маклая, д. 6

## Title
title: "Доклад"
subtitle: "Система инициализации runit"
license: "CC BY"
---

# Цель работы

Целью данного доклада является изучение архитектуры, сильные и слабые стороны Runit как системы инициализации и инструмента управления сервисами.

# Теоретическое введение

В мире Linux долгое время доминировала система SysVinit. Она работала по простому принципу: последовательно запускала скрипты. Однако с развитием технологий (серверы с большим количеством ядер, частое переподключение устройств, контейнеризация) её недостатки стали критическими: медленная загрузка и хрупкая система зависимостей.

На смену ей пришли современные решения. Systemd, ставший стандартом де-факто, предложил скорость и функциональность, но получил прозвище «тяжеловесным» за нарушение философии Unix («программа должна делать одно дело, но хорошо»). Runit, созданный Герритом Папе (Gerrit Pape) в 2004 году, стал ответом тем, кто хотел сохранить Unix-way: модульность, простоту и надёжность

# Философия и архитектура

Runit позиционируется как легковесная, модульная и портируемая утилита. В отличие от Systemd, который стремится контролировать всё (логи, сеть, таймеры, монтирование), Runit занимается только тем, для чего предназначен — порождением процессов и наблюдением за ними

Трехстадийная модель (The 3 Stages)
Ключевая особенность Runit — разделение процесса загрузки на три четких этапа:

1. Стадия 1 (Одноразовая инициализация): Выполняется скрипт /etc/runit/1. Здесь монтируются файловые системы, настраивается аппаратное обеспечение и загружаются модули ядра. Если скрипт завершается с ошибкой, система переходит в режим восстановления.
2. Стадия 2 (Супервизор): Запускается программа runsvdir, которая проверяет директорию сервисов (обычно /etc/service). Именно на этом этапе система «оживает»: параллельно запускаются сеть, SSH, cron и другие.
3. Стадия 3 (Остановка): Выполняется скрипт /etc/runit/3. Он убивает оставшиеся процессы, размонтирует диски и готовит систему к выключению или перезагрузке.

# Управление сервисами: Как это работает

В Runit управление сервисами радикально отличается от привычных systemctl или скриптов init.d.

Принцип "Каталог = Сервис": Каждый сервис — это просто директория с файлом run (исполняемым скриптом или бинарным файлом)

Отсутствие сложных конфигураций: Нет централизованных файлов .service с синтаксисом INI или XML. Настройка — это shell-скриптинг.

Логирование: Рекомендуется использовать отдельный сервис-логгер (стандартный svlogd), который перехватывает stdout сервиса. Это сохраняет принцип Unix «разделения ответственности»

# Как включить/выключить сервис?

Управление происходит через создание или удаление символических ссылок в директории /etc/service (или /var/service). Механизм runsvdir мониторит эту папку в реальном времени: если ссылка появилась — сервис запускается, исчезла — убивается

Пример базового сервиса (/etc/sv/myapp/run):

#!/bin/sh

exec my_app_daemon >> /var/log/myapp.log 2>&1

Запуск сервиса осуществляется командой ln -s /etc/sv/myapp /etc/service/.

# Преимущества и недостатки

В [табл. @tbl-positives-negatives] приведены основные преймущества и недостатки runit.

| Преймущества        | Недостатки                   |                                                                                      
|---------------------|------------------------------|
| Истинная простота   | Ручная работа                |                                                              
| Скорость и ресурсы  | Меньшая функциональность     |
| Надёжный супервизор | Сообщество                   |                      
                                                                                

: Преймущества и недостатки {#tbl-positives-negatives}

# Применение

Runit является стандартной системой инициализации для следующих дистрибутивов:

1. Void Linux: Самый известный представитель. Выбор Runit обусловлен желанием оставаться простым и прозрачным.

2. AntiX: Легковесный дистрибутив для старого оборудования. Runit там используется для ускорения загрузки

3. Dragora GNU/Linux-Libre: Дистрибутив, полностью свободный от проприетарных компонентов

Также Runit часто используется не как PID 1, а как инструмент пользователя для поддержания работы фоновых процессов в сессии

# Выводы

runit - это пример следования принципу KISS (Keep It Simple, Stupid). В мире, где системное программное обеспечение становится всё более монолитным, Runit предлагает глоток свежего воздуха: прозрачный код и предсказуемое поведение.

Однако, за простоту приходится платить удобством автоматизации. Runit идеально подходит для контейнеров, встраиваемых систем и минималистичных серверов, где каждый мегабайт памяти на счету и нет необходимости в сложной логике зависимостей. Для десктопа с GNOME или сложного корпоративного сервера с десятками связанных сервисов, Systemd, несмотря на свою сложность, предоставляет гораздо более удобные инструменты управления.

# Список литературы{.unnumbered}


1. {#https://ipfs.io/ipfs/QmehSxmTPRCr85Xjgzjut6uWQihoTfqg9VVihJ892bmZCp/Runit.html}
2. {#https://ru.wikipedia.org/wiki/Runit}
3. {#https://manpages.debian.org/trixie/runit/runit-init.8.en.html}
4. {#https://spandanmandal.hashnode.dev/a-guide-to-runit-discovering-an-efficient-and-minimal-init-system}
5. {#https://wiki.archlinux.org/title/Runit}


